### ISSUE TITLE
Cursor position is off on popup field

### ISSUE THREAD

**Issue by dinolatoga** [kieranju/accents-ui#1]
When you try to rename or create a file from tree view ( right click > rename ), a popup field appears and the cursor is one space off.

**Comment by kieranju** [comment]
Yup, this seems to be a thing -- testing it out under atom's default theme does not have any misalignments. I'll check out what might be causing it and issue a fix soon!

Thanks for submitting your find!

**Comment by dinolatoga** [comment]
Cool. Looking forward to the fix.

**Comment by kieranju** [comment]
It was difficult to pinpoint what the cause was, as the popup module would not let me dabble in the code inspector – it would immediately disappear upon losing focus. Eventually discovered that it was to do with a transition I applied to the module popups. Oddly enough, the cursor wasn't really displaced in the Command Palette, or any other popups other than when you rename a file!

Grab the newest minor update (v0.4.0) for the changes :+1:

**Comment by dinolatoga** [comment]
[Update] It works!
Thanks! I'll give it a try.
